### ISSUE TITLE
Tabbed toc not rendering correctly

### ISSUE THREAD

**Issue by ldorigo** [Jermolene/TiddlyWiki5#3211]
Issue present on Chrome, Firefox and Safari on macOS. Using node server.

Here is the html of the tiddler: (click on 'bus' to see the problem)
[Chapter 6_ Input and Output.html.zip](https://github.com/Jermolene/TiddlyWiki5/files/1902148/Chapter.6_.Input.and.Output.html.zip)

Screenshot:
<img width="1161" alt="screenshot 2018-04-12 10 47 51" src="https://user-images.githubusercontent.com/8631181/38666505-5f6faa38-3e3f-11e8-8b62-933f63af1422.png">

**Comment by Jermolene** [comment]
Hi @ldorigo I think this is fixed in 7e71fcfab80bed9aed4389eea386fb2036cc4a85, available in the prerelease. Could you give it a try? See [here](https://tiddlywiki.com/#Installing%20TiddlyWiki%20Prerelease%20on%20Node.js) for instructions on running the latest prerelease under Node.js.

**Comment by pmario** [comment]
uups: I was testing: ControlPanel: Appearence: Toolbars: EditToolbar with a small browser . .. Has the same problem with the list items. .... 

So not the problem mentioned here :/

**Comment by pmario** [comment]
testing with: 

```
.tc-tabbed-table-of-contents {
    display: -webkit-flex;
    display: flex;
}
```

for the wrapper element. ...

**Comment by ldorigo** [comment]
Sorry @Jermolene had a busy time between exams and having to change computer, couldn't try this out before. 

I just tested with the prerelease, the issue is still present. Let me know if you need any extra info.

**Comment by pmario** [comment]
@ldorigo .. Do you still use TiddylWiki. Is this still an issue? I can not replicate it.

**Comment by pmario** [comment]
Issue is not replicable anymore
